name: cname_flatten

env:
  TZ: Asia/Shanghai

on:
  workflow_dispatch:
  schedule:
    # 分钟 小时 日期 月份 星期（0-6）//0代表星期天
    - cron: '0 * * * *'
    - cron: '15 * * * *'
    - cron: '30 * * * *'
    - cron: '45 * * * *'
    - cron: '59 * * * *'
  push:
    branches: [ main ]
    paths:
      - 'cname_flatten/**'
      - '.github/workflows/cname_flatten.yml'
      - '.github/workflows/cron.yml'

jobs:
  # ipv6:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Setup WARP
  #       uses: fscarmen/warp-on-actions@v2
  #     - name: ipv6
  #       run: |
  #         set -x
  #         curl -m6 -i https://i18n.site/.i || true
  #         curl -m6 -i --resolve "i18n.site:443:111.63.51.41" https://i18n.site/.i || true
  #         curl -m6 -i --resolve "i18n.site:443:111.63.1.1" https://i18n.site/.i || true
  #         curl -m9 -6 https://ifconfig.co || true
  cname_flatten:
    uses: ./.github/workflows/cron.yml
    with:
      name: cname_flatten
    secrets: inherit
